version: '3.5'
services:
    mongo:
        image: 'mongo:latest'
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - './mongodb/data:/data/db'
    backend:
        build:
          context: .
          dockerfile: ./backend/Dockerfile
        ports:
            - '4000:4000'
        depends_on:
            - mongo
    frontend:
        build:
          context: .
          dockerfile: ./frontend/Dockerfile
        ports:
            - '3000:3000'
