version: '3'
services:
    mongo:
        image: 'mongo:latest'
        restart: always
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - './mongo/data:/data/db'
    backend:
        # container_name: backend
        restart: always
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '4000:4000'
        depends_on:
            - mongo
    frontend:
        restart: always
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
