version: '3'
services:
    mongo:
        image: 'mongo:latest'
        restart: always
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - './mongodb/data:/data/db'
    backend:
        # container_name: backend
        restart: always
        build: 
            dockerfile: Dockerfile
            context: ./backend
        ports:
            - '4000:4000'
        external_links:
            - mongo
    frontend:
        restart: always
        build:
          dockerfile: Dockerfile
          context: ./frontend
        ports:
            - '3000:3000'
